#SYSTEM:
#  NUM_GPUS: 2
#  NUM_CPUS: 8
MODEL:
  INPUT_SIZE: [6, 96, 96]
  OUTPUT_SIZE: [6, 96, 96]
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ["2"]
  LABEL_EROSION: 1
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss", "DiceLoss"]]
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
DATASET:
  OUTPUT_PATH: /ygs/personal/chengao/connectomics_project/ft_model/unetr_affinity_ct/
  PAD_SIZE: [3, 48, 48]
  DISTRIBUTED: True
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.02
  ITERATION_STEP: 1
  ITERATION_SAVE: 10000
  ITERATION_TOTAL: 150000
  WARMUP_ITERS: 5000
  SAMPLES_PER_BATCH: 4
MONITOR:
  ITERATION_NUM: [200, 1000]
INFERENCE:
  OUTPUT_PATH: outputs/SNEMI_UNETR/aff_40k_ct/
